name: Web CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter --suppress-analytics config --no-analytics
      - run: flutter config --enable-web
      - run: flutter pub get

      - name: Build web release
        run: flutter build web --web-renderer canvaskit

      - name: Publish web release
        run: |
          cd build/web
          git init
          git config user.name "Epimetheus CD"
          git config user.email "cd@epimetheus.tk"
          git remote add secure-origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout -b www
          git add .
          git commit -m "Built web release from $GITHUB_SHA"
          git push --force secure-origin www
          cd -
      - name: Purge Cloudflare caches
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
